name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.0'
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: List dependencies
        run: bun pm ls --all
      - name: Build
        run: bun run main.js
      - name: Upload artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            *.png
